### ISSUE TITLE
License terms?

### ISSUE THREAD

**Issue by gkelly** [esden/pretty-kicad-libs#13]
What are the licensing terms for this repository?

**Comment by esden** [comment]
Unfortunately I can't really put a license on this repository. It is a bit of a mixed bag because I am adding 3d models from vendors, modify existing symbols and footprints. I use this library more as a convenience and time saving for my project than anything else. I probably should start tracking the source of the symbols and footprints.

**Comment by gkelly** [comment]
Understood, thanks for the clarification!
